import type { Metadata } from "next";
import { DM_Serif_Text, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import Footer from "@/components/footer";

const dmSerifText = DM_Serif_Text({
  variable: "--font-dm-serif-text",
  subsets: ["latin"],
  weight: "400"
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifText.variable} ${dmSerifDisplay.variable} antialiased container mx-auto bg-[#f4efe69f] text-[#55534f] `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
